name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install yarn

      - name: Install Expo CLI
        run: yarn add expo-cli

      - name: Log in to Expo
        run: yarn expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      - name: Install EAS CLI
        run: yarn add @expo/eas-build-job

      - name: Check EAS CLI
        run: yarn eas --version

      - name: Install dependencies
        run: yarn install

      - name: Build Android
        run: yarn eas build -p android

      - name: Build iOS
        run: npx eas build -p ios
        continue-on-error: true
